                <footer <?php echo (strpos($url, 'theissue') !==  false) ? 'id="theIssueFooter"' : ''; ?> >
                    <hr class="privacyhr" />
                    <a id="privacy" href="#">PRIVACY POLICY <span>+</span></a>
                    <div id="privacyExpand">
                        <p>THORN is committed to providing information and activities relating to THORN'S mission on the website. While we encourage the interactive nature of our website, we strive to promote the online safety and privacy of our users.</p>
                        <p>Information You Provide to Us: We collect information about you when you visit and interact with this site. Some of this information is automatically collected, and some is collected when you interact with the site. The type of information that is automatically collected can include date and time of access of the site, the Internet protocol address of the computer that you are using, the domain and host from which you access the Internet, your browser software and operating system, and the specific activities you are engaged in while visiting the site. Information from which you can be personally identified may also be collected by us at the site, including your name and email address.</p>
                        <p>Linked Sites: From time to time, the website may contain links to other websites that are not controlled and/or maintained by THORN. Please be aware that these other websites may have different privacy policies which may subject you to different privacy practices. Please review the privacy policies of such other websites for information concerning what information is collected on such sites and how it is used.</p>
                        <p>If you have registered to receive e-mail communications from us and later change your mind, you may contact us to have your name removed from our distribution lists. To opt out, you can send an e-mail to: info (at) wearethorn.org with UNSUBSCRIBE in the subject line.</p>
                    </div>
                </footer>